################################################################################
# Common Settings
################################################################################
# Usage:
#   Add the following code to package section in the device file
# ------------------------------------------------------------------------------
# packages:
#   board: !include common/settings.yaml
# ------------------------------------------------------------------------------
# Author: Pascal Parent
# Company: Home Automator (ZA)
# Web: https://www.youtube.com/@homeautomatorza
# Version: 1.2.0
# Licence: CCO 1.0 https://creativecommons.org/publicdomain/zero/1.0/
# ------------------------------------------------------------------------------
# WARNING:
# This code carries a "It works on my setup" disclaimer!
# Meaning that it works on my setup but it may not work on yours.
################################################################################
# ESPHome Configuration
################################################################################
esphome:
  name: ${device_internal_name}
  friendly_name: ${device_friendly_name}

################################################################################
# Enable logging
################################################################################
logger:

################################################################################
# Enable Home Assistant API
################################################################################
api:
  id: ${device_internal_name}_ha_api
  encryption:
    key: !secret api_encryption_key
  reboot_timeout: 0s

################################################################################
# OTA Settings
################################################################################
ota:
  platform: esphome
  password: !secret web_server_password

safe_mode:
  disabled: false
  reboot_timeout: 10min
  num_attempts: 5

################################################################################
# Network Settings
################################################################################
# Ensure mDNS is enabled
mdns:
  disabled: false

# Disable IPV6
network:
    enable_ipv6: false

################################################################################
# Binary Sensors
################################################################################
binary_sensor:
  # ESP Status Sensor
  - platform: status
    id: ${device_internal_name}_status
    name: "Status"
    icon: mdi:network-pos
    disabled_by_default: true

################################################################################
# Sensors
################################################################################
sensor:
  # Human Readable Uptime Conversion Sensor
  - platform: uptime
    id: ${device_internal_name}_uptime_sensor
    name: Uptime Sensor
    on_raw_value:
      then:
        - text_sensor.template.publish:
            id: ${device_internal_name}_uptime_human
            state: !lambda |-
              int seconds = round(id(${device_internal_name}_uptime_sensor).raw_state);
              int days = seconds / (24 * 3600);
              seconds = seconds % (24 * 3600);
              int hours = seconds / 3600;
              seconds = seconds % 3600;
              int minutes = seconds /  60;
              seconds = seconds % 60;
              return (
                (days ? to_string(days) + "d " : "") +
                (hours ? to_string(hours) + "h " : "") +
                (minutes ? to_string(minutes) + "m " : "") +
                (to_string(seconds) + "s")
              ).c_str();
    internal: true
    update_interval: ${device_sampling_time}
    disabled_by_default: true


################################################################################
# Text Sensors
################################################################################
text_sensor:
  # ESP32 Version Sensor
  - platform: version
    id: ${device_internal_name}_version
    name: "ESPHome Version"
    hide_timestamp: true
    disabled_by_default: true

  # Human Time Text Sensors
  - platform: template
    id: ${device_internal_name}_uptime_human
    name: Uptime Human Readable
    icon: mdi:clock-start
    entity_category: diagnostic

################################################################################
# Switch
################################################################################
switch:
  # Soft Restart the device
  - platform: restart
    id: ${device_internal_name}_device_restart
    name: Restart

  # Restart the device in Safe Mode
  - platform: safe_mode
    id: ${device_internal_name}_device_safe_mode
    name: Use Safe Mode
    disabled_by_default: true

