################################################################################
# BME280 Temperature, Pressure and Humidity Sensor
################################################################################
# Usage:
#   Add the following code to package section in the device file changing the 
#   I2C Address to the appropriate one.
# -----------------------------------------------------------------------------
# packages:
#  bme280: !include 
#    file: sensors/i2c/bme280.yaml
#    vars:
#      i2c_address: 0x77
# ------------------------------------------------------------------------------
# Author: Pascal Parent
# Company: Home Automator (ZA)
# Web: https://www.youtube.com/@homeautomatorza
# Version: 1.1.0
# Licence: CCO 1.0 https://creativecommons.org/publicdomain/zero/1.0/
# Reference: https://esphome.io/components/sensor/bme280
# ------------------------------------------------------------------------------
# WARNING:
# This code carries a "It works on my setup" disclaimer!
# Meaning that it works on my setup but it may not work on yours.
################################################################################
sensor:
  - platform: bme280_i2c
    address: ${i2c_address}
    temperature:
      id: ${device_internal_name}_bme280_temperature
      oversampling: 16x
      on_value:
        then:
          - component.update: ${device_internal_name}_bme280_temperature_f
          - component.update: ${device_internal_name}_bme280_temperature_c
      internal: true
      disabled_by_default: true
    pressure:
      id: ${device_internal_name}_bme280_pressure_internal
      on_value:
        then: 
          - component.update: ${device_internal_name}_bme280_pressure
      internal: true
      disabled_by_default: true
    humidity:
      id: ${device_internal_name}_bme280_humidity_internal
      on_value:
        then: 
          - component.update: ${device_internal_name}_bme280_humidity
      internal: true
      disabled_by_default: true
    update_interval: ${device_sampling_time}

  # Temparature Fahrenheit
  - platform: template
    id: ${device_internal_name}_bme280_temperature_f
    name: BME280 Temperature (F)
    icon: mdi:temperature-fahrenheit
    unit_of_measurement: '°F'
    lambda: return id(${device_internal_name}_bme280_temperature_c).state * 9/5+32;
    device_class: temperature
    update_interval: never
    disabled_by_default: true

  # Temperature Celsius
  - platform: template
    id: ${device_internal_name}_bme280_temperature_c
    name: SHT40 Temperature (C)
    icon: mdi:temperature-celsius
    unit_of_measurement: '°C'
    lambda: return id(${device_internal_name}_bme280_temperature).state;
    device_class: temperature
    update_interval: never

  # Humidity
  - platform: template
    id: ${device_internal_name}_bme280_humidity
    name: SHT40 Humidity
    icon: mdi:water-percent
    unit_of_measurement: '%'
    lambda: return id(${device_internal_name}_bme280_humidity_internal).state;
    device_class: humidity
    update_interval: never

  # Pressure
  - platform: template
    id: ${device_internal_name}_bme280_pressure
    name: BMP280 Atmospheric Pressure
    icon: mdi:gauge
    unit_of_measurement: 'hPa'
    lambda: return id(${device_internal_name}_bme280_pressure_internal).state;
    device_class: atmospheric_pressure
    update_interval: never

  # Dew Point
  - platform: template
    name: "BME280 Dew Point"
    id: ${device_internal_name}_bme280_dew_point
    lambda: |-
      return (243.5*(log(id(${device_internal_name}_bme280_humidity).state/100)+((17.67*id(${device_internal_name}_bme280_temperature).state)/
      (243.5+id(${device_internal_name}_bme280_temperature).state)))/(17.67-log(id(${device_internal_name}_bme280_humidity).state/100)-
      ((17.67*id(${device_internal_name}_bme280_temperature).state)/(243.5+id(${device_internal_name}_bme280_temperature).state))));
    unit_of_measurement: °C
    icon: 'mdi:thermometer-alert'
