################################################################################
# Generic ESP32-C3 OLED 0.42" Display
################################################################################
# Usage:
#   Add the following code to package section in the device file
# ------------------------------------------------------------------------------
# packages:
#   board: !include boards/esp32/c3-oled-0-42-display.yaml
# ------------------------------------------------------------------------------
# Author: Pascal Parent
# Company: Home Automator (ZA)
# Web: https://www.youtube.com/@homeautomatorza
# Version: 1.0.0
# Licence: CCO 1.0 https://creativecommons.org/publicdomain/zero/1.0/
# ------------------------------------------------------------------------------
# Notes:
#     - Warning, this board does not use standard I2C and UART GPIO due to LED conflict!
# ------------------------------------------------------------------------------
# Referance: https://www.espboards.dev/esp32/esp32-c3-oled-042/
# Spec: 
#     - ESP32C3FN4 RISC-V 32-bit Single Core (160 MHz)
#     - 2.4 GHz (802.11ax b/g/n)
#     - Bluetooth 5 module
#     - 400KB SRAM
#     - 384KB ROM
#     - 4 MB Flash
#     - 1 × I2C
#     - 1 × I2S
#     - 1 x SPI
#     - 2 x UART
#     - 6 × 12-bit SAR ADC
#     - 1 x LED
#     - 1 x Internal Temperature Sensor
#     - 0.42" OLED I2C Screen (72x40 resolution)
#     - SSD1306 display controller
# ------------------------------------------------------------------------------
# Notes:
#     - Uses Arduino IDE standard pins
#     - Status LED should be disabled by default to avoid clash with I2C 
# ------------------------------------------------------------------------------
# WARNING:
# This code carries a "It works on my setup" disclaimer!
# Meaning that it works on my setup but it may not work on yours.
# Use at your own risks!
################################################################################
esp32:
  board: esp32-c3-devkitm-1
  variant: esp32c3
  flash_size: 4MB
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_ESPTOOLPY_FLASHSIZE_4MB: y # Ensures a 4MB flash size
      CONFIG_ENABLE_WIFI_STATION: y     # Ensures the WiFi is up
      CONFIG_USE_MINIMAL_MDNS: y

# Internal RGB LED
light:
  - platform: esp32_rmt_led_strip
    id: ${device_internal_name}_onboard_rgb_led
    name: Onboard RGB LED
    icon: mdi:led-outline
    rgb_order: GRB
    pin: GPIO2
    num_leds: 1
    restore_mode: ALWAYS_OFF
    chipset: ws2812
    entity_category: config
    disabled_by_default: true

# I2C settings
i2c:
  id: ${device_internal_name}_i2c
  sda: GPIO5
  scl: GPIO6
  scan: false

# UART
uart:
  id: ${device_internal_name}_uart_bus0
  tx_pin: GPIO21
  rx_pin: GPIO20
  baud_rate: 256000
  parity: NONE
  stop_bits: 1

# SPI
spi:
  id: ${device_internal_name}_spi_bus0
  clk_pin: GPIO10
  miso_pin: GPIO8
  mosi_pin: GPIO7
  interface: hardware

# Sensors
sensor:
  # Internal Temperature Sensor
  - platform: internal_temperature
    id: ${device_internal_name}_internal_temperature
    name: "Internal Temperature"
    icon: mdi:temperature-celsius
    update_interval: ${device_sampling_time}
    disabled_by_default: true

  - platform: template
    id: ${device_internal_name}_internal_temperature_f
    name: Internal Temperature Temperature (F)
    icon: mdi:temperature-fahrenheit
    unit_of_measurement: °F
    lambda: return id(${device_internal_name}_internal_temperature).state * 9/5+32;
    device_class: temperature
    entity_category: diagnostic
    update_interval: ${device_sampling_time}
    disabled_by_default: true

# Board Model for Referance
text_sensor:
  - platform: template
    name: Board Model
    id: ${device_internal_name}_board
    lambda: |-
      return {"ESP32-C3 OLED 0.42inch Display"};
    icon: mdi:cpu-32-bit
    entity_category: diagnostic
    update_interval: ${device_sampling_time}
    disabled_by_default: true