################################################################################
# Makerfabs MaTouch_ESP32-C3(RISC-V) SPI TFT Touch 3.5" ILI9488
################################################################################
# Usage:
#   Add the following code to package section in the device file
# ------------------------------------------------------------------------------
# packages:
#   board: !include boards/esp32/c3_mini_matouch.yaml
# ------------------------------------------------------------------------------
# Author: Pascal Parent
# Company: Home Automator (ZA)
# Web: https://www.youtube.com/@homeautomatorza
# Version: 1.0.0
# Licence: CCO 1.0 https://creativecommons.org/publicdomain/zero/1.0/
# ------------------------------------------------------------------------------
# Notes:
#     - Tested OK
# ------------------------------------------------------------------------------
# Referance: https://www.makerfabs.com/ep32-c3-risc-v-spi-tft-touch.html
# Spec: 
#     - ESP32-C3FN4 RISCV Single Core 
#     - 2.4 GHz Wi­Fi (802.11 b/g/n) and Bluetooth 5 module
#     - 4 MB flash
#     - 400KB SRAM
#     - 3.5inch TFT SPI LCD 480*320 (ILI9488)
#     - Capacitive Touch (FT6236)
#     - 1 × I2C
#     - 1 × MicroSD Card (Unused)
#     - 1 x Internal Temperature Sensor
# ------------------------------------------------------------------------------
# WARNING:
# This code carries a "It works on my setup" disclaimer!
# Meaning that it works on my setup but it may not work on yours.
# Use at your own risks!
################################################################################
esp32:
  board: esp32-c3-devkitm-1
  flash_size: 4MB
  framework:
  # type: arduino
  # version: latest
    type: esp-idf
    version: 5.2.1 
    platform_version: 6.6.0 
    sdkconfig_options:
      CONFIG_ESPTOOLPY_FLASHSIZE_4MB: y # Ensures a 4MB flash size
      CONFIG_OPENTHREAD_ENABLED: n      # Disable Thread!
      CONFIG_ENABLE_WIFI_STATION: y     # Ensures the WiFi is up
      CONFIG_USE_MINIMAL_MDNS: y
      
# -------------------------------------------------------------------------------
# I2C
# -------------------------------------------------------------------------------
i2c:
  id: ${device_internal_name}_i2c
  sda: GPIO2
  scl: GPIO3
  scan: true

# -------------------------------------------------------------------------------
# SPI
# -------------------------------------------------------------------------------
spi:
  id: ${device_internal_name}_spi_bus0
  clk_pin: GPIO5
  mosi_pin: GPIO6
  miso_pin: GPIO7
  interface: hardware

# -------------------------------------------------------------------------------
# Sensors
# -------------------------------------------------------------------------------
sensor:
  # Internal Temperature Sensor
  - platform: internal_temperature
    id: ${device_internal_name}_internal_temperature
    name: "Internal Temperature"
    update_interval: ${device_sampling_time}
    disabled_by_default: true

# -------------------------------------------------------------------------------
# Display - Try to use with LVGL Graphics - Put LVGL in device file
# -------------------------------------------------------------------------------
display:
  - platform: ili9xxx
    id: ${device_internal_name}_display
    model: ILI9488
    cs_pin: GPIO4
    dc_pin: GPIO10
    dimensions:
      height: 480
      width: 320
    rotation: 270°
    color_order: rgb
    auto_clear_enabled: false
    update_interval: never

output:
  - platform: ledc
    id: ${device_internal_name}_backlight_pwm
    pin: GPIO8 

light:
  - platform: monochromatic
    id: ${device_internal_name}_backlight
    name: "Display Backlight"
    icon: mdi:brightness-7
    restore_mode: ALWAYS_ON
    output: ${device_internal_name}_backlight_pwm
    entity_category: config

# -------------------------------------------------------------------------------
# FT6236 Touch screen @ I2C 0x38
# -------------------------------------------------------------------------------
#touchscreen:
#  platform: ft63x6
#  id: ${device_internal_name}_touchscreen
#  reset_pin: GPIOx
#  interrupt_pin: GPIOx
