################################################################################
# Espressif ESP32 C3 Super Mini v1
################################################################################
# Usage:
#   Add the following code to package section in the device file
# ------------------------------------------------------------------------------
# packages:
#   board: !include boards/esp32/c3_super_mini.yaml
# ------------------------------------------------------------------------------
# Author: Pascal Parent
# Company: Home Automator (ZA)
# Web: https://www.youtube.com/@homeautomatorza
# Version: 1.0.0
# Licence: CCO 1.0 https://creativecommons.org/publicdomain/zero/1.0/
# ------------------------------------------------------------------------------
# Notes:
#     - Warning, this board does not use standard I2C and UART GPIO due to LED conflict!
# ------------------------------------------------------------------------------
# Referance: https://www.espboards.dev/esp32/esp32-c6-super-mini/ 
# Spec: 
#     - ESP32C3FN4 RISC-V 32-bit Single Core (160 MHz)
#     - 2.4 GHz (802.11ax b/g/n)
#     - Bluetooth 5 module
#     - 400KB SRAM
#     - 384KB ROM
#     - 4 MB Flash
#     - 1 × I2C
#     - 1 × I2S
#     - 1 x SPI
#     - 2 x UART
#     - 4 × 12-bit SAR ADC
#     - 1 x LED
#     - 1 x Internal Temperature Sensor
# ------------------------------------------------------------------------------
# Notes:
# ------------------------------------------------------------------------------
# WARNING:
# This code carries a "It works on my setup" disclaimer!
# Meaning that it works on my setup but it may not work on yours.
# Use at your own risks!
################################################################################
esp32:
  board: esp32-c3-devkitm-1
  variant: esp32c3
  flash_size: 4MB
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_ESPTOOLPY_FLASHSIZE_4MB: y # Ensures a 4MB flash size
      CONFIG_ENABLE_WIFI_STATION: y     # Ensures the WiFi is up
      CONFIG_USE_MINIMAL_MDNS: y

# Internal LEDs 
# Note: disble if I2C is used
status_led:
  id: ${device_internal_name}_status_led
  pin:
    number: GPIO8
    inverted: true

# I2C settings
i2c:
  id: ${device_internal_name}_i2c
  sda: GPIO9
  scl: GPIO10
  scan: true

# UART
uart:
  id: ${device_internal_name}_uart_bus0
  tx_pin: GPIO21
  rx_pin: GPIO20
  baud_rate: 256000
  parity: NONE
  stop_bits: 1

# SPI
spi:
  id: ${device_internal_name}_spi_bus0
  clk_pin: GPIO4
  miso_pin: GPIO5
  mosi_pin: GPIO6
  interface: hardware

# Sensors
sensor:
  # Internal Temperature Sensor
  - platform: internal_temperature
    id: ${device_internal_name}_internal_temperature
    name: "Internal Temperature"
    icon: mdi:temperature-celsius
    update_interval: ${device_sampling_time}
    disabled_by_default: true

  - platform: template
    id: ${device_internal_name}_internal_temperature_f
    name: Internal Temperature Temperature (F)
    icon: mdi:temperature-fahrenheit
    unit_of_measurement: °F
    lambda: return id(${device_internal_name}_internal_temperature).state * 9/5+32;
    device_class: temperature
    entity_category: diagnostic
    update_interval: ${device_sampling_time}
    disabled_by_default: true

# Board Model for Referance
text_sensor:
  - platform: template
    name: Board Model
    id: ${device_internal_name}_board
    lambda: |-
      return {"Espressif ESP32 C3 Super Mini v1"};
    icon: mdi:cpu-32-bit
    entity_category: diagnostic
    update_interval: ${device_sampling_time}
    disabled_by_default: true