################################################################################
# Super Mini ESP32-C6 v1.0
################################################################################
# Usage:
#   Add the following code to package section in the device file
# ------------------------------------------------------------------------------
# packages:
#   board: !include boards/esp32/c6_firebeetle_2.yaml
# ------------------------------------------------------------------------------
# Author: Pascal Parent
# Company: Home Automator (ZA)
# Web: https://www.youtube.com/@homeautomatorza
# Version: 0.1.0 Beta
# Licence: CCO 1.0 https://creativecommons.org/publicdomain/zero/1.0/
# ------------------------------------------------------------------------------
# Notes: 
#       - Warning, this board does not use standard I2C and UART GPIO due to LED conflict!
# ------------------------------------------------------------------------------
# Referance: https://www.espboards.dev/esp32/esp32-c6-super-mini/ 
# Spec: 
#     - ESP32C6FH4 RISC-V 32-bit Single Core (160MHz)
#     - 2.4 GHz Wi­Fi (802.11 ax b/g/n) and Bluetooth 5.3 module 
#     - Zigbee/Thread Capable
#     - 4 MB flash
#     - 512KB high-performance SRAM and 16 KB low-power SRAM
#     - 1 × I2C
#     - 6 analog input pins
#     - 11 PWM pins
#     - 1 x Internal Temperature Sensor
# ------------------------------------------------------------------------------
# WARNING:
# This code carries a "It works on my setup" disclaimer!
# Meaning that it works on my setup but it may not work on yours.
################################################################################
esp32:
  board: esp32-c6-devkitc-1
  variant: esp32c6
  flash_size: 4MB
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_ESPTOOLPY_FLASHSIZE_4MB: y # Ensures a 4MB flash size
      CONFIG_OPENTHREAD_ENABLED: n      # Disable Thread!
      CONFIG_ENABLE_WIFI_STATION: y     # Ensures the WiFi is up
      CONFIG_USE_MINIMAL_MDNS: y

# Status led
status_led:
  id: ${device_internal_name}_status_led
  pin:
    number: GPIO15
    inverted: false

# Internal RGB LED
light:
  - platform: esp32_rmt_led_strip
    id: ${device_internal_name}_onboard_rgb_led
    name: Onboard RGB LED
    icon: mdi:led-outline
    rgb_order: GRB
    pin: GPIO8
    num_leds: 1
    restore_mode: ALWAYS_OFF
    chipset: ws2812
    entity_category: config
    disabled_by_default: true

# I2C settings
i2c:
  - id: ${device_internal_name}_i2c_bus0
    sda: GPIO14
    scl: GPIO18
    scan: true

# UART
uart:
  - id: ${device_internal_name}_uart_bus0
    tx_pin: GPIO19
    rx_pin: GPIO20
    baud_rate: 256000
    parity: NONE
    stop_bits: 1

# SPI
spi:
  id: ${device_internal_name}_spi_bus0
  clk_pin: GPIO4
  miso_pin: GPIO5
  mosi_pin: GPIO6
  interface: hardware

# Sensors
sensor:
  # Internal Temperature Sensor
  - platform: internal_temperature
    id: ${device_internal_name}_internal_temperature
    name: "Internal Temperature"
    icon: mdi:temperature-celsius
    update_interval: ${device_sampling_time}
    disabled_by_default: true

  - platform: template
    id: ${device_internal_name}_internal_temperature_f
    name: Internal Temperature (F)
    icon: mdi:coolant-temperature
    unit_of_measurement: °F
    lambda: return id(${device_internal_name}_internal_temperature).state * 9/5+32;
    device_class: temperature
    update_interval: ${device_sampling_time}
    entity_category: diagnostic
    disabled_by_default: true

