################################################################################
# Non-Contact Digital Water Level Sensor
################################################################################
# Usage:
#   Add the following code to package section in the device file changing the 
#   GPIO pin to the appropriate one.
# -----------------------------------------------------------------------------
# packages:
#  xkc-y25-t12v: !include 
#    file: sensors/binary/xkc-y25-t12v.yaml
#    vars:
#      pin: GPIO14
# ------------------------------------------------------------------------------
# Author: Pascal Parent
# Company: Home Automator (ZA)
# Web: https://www.youtube.com/@homeautomatorza
# Version: 1.0.0
# Licence: CCO 1.0 https://creativecommons.org/publicdomain/zero/1.0/
# Reference: https://esphome.io/components/switch/gpio.html
# ------------------------------------------------------------------------------
# WARNING:
# This code carries a "It works on my setup" disclaimer!
# Meaning that it works on my setup but it may not work on yours.
################################################################################
binary_sensor:
  - platform: gpio
    name: Water Level
    id: ${device_internal_name}_water_level
    icon: mdi:hydraulic-oil-level
    pin: ${pin}